-- RAW Coffee seed — شغّله بعد schema.sql. الأسعار تقديرية (متناسبة مع الوزن) وتتعدل من لوحة الأدمن.
begin;
insert into public.categories(id,name_ar,name_en,image_url,sort) values('بن سادة','بن سادة','Plain Coffee','https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=85',0);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('بن محوج','بن محوج','Spiced Coffee','https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1000&q=85',1);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('بن فرنسي','بن فرنسي','French Coffee','https://images.unsplash.com/photo-1459755486867-b55449bb39ff?auto=format&fit=crop&w=1000&q=85',2);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('إسبريسو','إسبريسو','Espresso','https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=1000&q=85',3);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('قهوة عربي','قهوة عربي','Arabic Coffee','https://images.unsplash.com/photo-1522992319-0365e5f11656?auto=format&fit=crop&w=1000&q=85',4);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('أدوات القهوة','أدوات القهوة','Coffee Tools','https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1000&q=85',5);
insert into public.categories(id,name_ar,name_en,image_url,sort) values('عروض وباكدجات','عروض وباكدجات','Bundles & Deals','https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=1000&q=85',6);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن سادة','بن ساده فاتح','مذاق متوازن ولمسة عطرية خفيفة، مناسب للقهوة اليومية.','https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=88','رائج','فاتح',array['فاتح','وسط','غامق']::text[],'balanced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,140,null,100,0),((select id from p),'500 جم',500,280,null,100,1),((select id from p),'1 كجم',1000,560,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن سادة','بن ساده وسط','توازن واضح بين قوة الفنجان وحلاوة التحميص.','https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=900&q=88','رائج','وسط',array['فاتح','وسط','غامق']::text[],'balanced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,140,null,100,0),((select id from p),'500 جم',500,280,null,100,1),((select id from p),'1 كجم',1000,560,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن سادة','بن ساده غامق','تحميص غامق لعشاق الفنجان القوي والنهاية الطويلة.','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=88','لعشاق القوي','غامق',array['وسط','غامق']::text[],'strong','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,150,null,100,0),((select id from p),'500 جم',500,300,null,100,1),((select id from p),'1 كجم',1000,600,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن محوج','بن محوج كلاسيك','مزيج محوج بطابع مصري واضح ومناسب للقهوة اليومية.','https://images.unsplash.com/photo-1461988091159-192b6df7054f?auto=format&fit=crop&w=900&q=88','اختيار البيت','غامق',array['وسط','غامق']::text[],'spiced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,165,null,100,0),((select id from p),'500 جم',500,330,null,100,1),((select id from p),'1 كجم',1000,660,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن محوج','بن محوج وسط','قهوة متوازنة مع رائحة بهارات خفيفة.','https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=900&q=88','الأكثر طلبًا','وسط',array['وسط','غامق']::text[],'spiced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,165,null,100,0),((select id from p),'500 جم',500,330,null,100,1),((select id from p),'1 كجم',1000,660,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن محوج','بن محوج غامق','خلطة أغنى لعشاق المحوج الثقيل والفنجان القوي.','https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=88',null,'غامق',array['غامق']::text[],'strong','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,155,null,100,0),((select id from p),'500 جم',500,310,null,100,1),((select id from p),'1 كجم',1000,620,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن فرنسي','بن فرنسي بندق','نكهة بندق ناعمة ولمسة عطرية دافئة.','https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=88','رائج','وسط',array['وسط','غامق']::text[],'smooth','french') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,155,null,100,0),((select id from p),'500 جم',500,310,null,100,1);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن فرنسي','بن فرنسي شوكولاتة','نكهة غنية بلمسة شوكولاتة محببة.','https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=900&q=88',null,'وسط',array['وسط','غامق']::text[],'smooth','french') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,155,null,100,0),((select id from p),'500 جم',500,310,null,100,1);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('بن فرنسي','بن فرنسي كراميل','ملمس ناعم ونهاية حلوة مناسبة لمحبي القهوة المنكهة.','https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=88','جديد','وسط',array['فاتح','وسط']::text[],'smooth','french') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,165,null,100,0),((select id from p),'500 جم',500,330,null,100,1);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('إسبريسو','إسبريسو كلاسيك','Blend مناسب للإسبريسو مع جسم قوي ونهاية واضحة.','https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=900&q=88',null,'غامق',array['وسط','غامق']::text[],'strong','espresso') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,183,null,100,0),((select id from p),'500 جم',500,365,null,100,1),((select id from p),'1 كجم',1000,730,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('إسبريسو','إسبريسو 1 كيلو','اختيار عملي للبيوت الكبيرة والكافيهات ومحبي الإسبريسو.','https://images.unsplash.com/photo-1611162458324-aae1eb412a1f?auto=format&fit=crop&w=900&q=88','للكافيهات','غامق',array['غامق']::text[],'strong','espresso') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'500 جم',500,365,null,100,0),((select id from p),'1 كجم',1000,730,null,100,1);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('قهوة عربي','قهوة عربي كلاسيك','طابع عربي عطري مناسب للضيافة والتحضير التقليدي.','https://images.unsplash.com/photo-1522992319-0365e5f11656?auto=format&fit=crop&w=900&q=88',null,'فاتح',array['فاتح','وسط']::text[],'smooth','arabic') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'250 جم',250,195,null,100,0),((select id from p),'500 جم',500,390,null,100,1),((select id from p),'1 كجم',1000,780,null,100,2);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('قهوة عربي','قهوة عربي ضيافة','عبوة كبيرة للمناسبات والضيافة والاستخدام المستمر.','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=88',null,'فاتح',array['فاتح','وسط']::text[],'smooth','arabic') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'500 جم',500,390,null,100,0),((select id from p),'1 كجم',1000,780,null,100,1);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('أدوات القهوة','سبرتاية سادة صغيرة','سبرتاية عملية للمساحات الصغيرة والتحضير اليومي.','https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=88',null,null,'{}',null,'turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'قطعة',0,270,null,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('أدوات القهوة','سبرتاية سادة متوسطة','حجم متوسط مناسب للاستخدام اليومي والاستضافة.','https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=88',null,null,'{}',null,'turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'قطعة',0,290,null,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('أدوات القهوة','سبرتاية سادة كبيرة','حجم أكبر لتحضير أكثر من فنجان بسهولة.','https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=88',null,null,'{}',null,'turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'قطعة',0,330,null,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('أدوات القهوة','سبرتاية منقوشة','قطعة تقديم وتحضير مناسبة للهدايا والضيافة.','https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=88','هدية',null,'{}',null,'turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'قطعة',0,290,null,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('عروض وباكدجات','علبة تجربة 3 خلطات','ثلاث اختيارات صغيرة تساعدك تجرّب أكثر من مزاج في طلب واحد.','https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=88','وفر 50 ج','متنوع',array['متنوع']::text[],'balanced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'750 جم',750,490,540,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('عروض وباكدجات','باكدج القهوة اليومية','مجموعة مناسبة للبيت تجمع منتجين أساسيين مع هدية بسيطة.','https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=900&q=88','الأفضل قيمة','متنوع',array['متنوع']::text[],'balanced','turkish') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'1 كجم',1000,660,720,100,0);
with p as (insert into public.products(category_id,name_ar,desc_ar,image_url,badge_ar,roast,roasts,taste,brew) values('عروض وباكدجات','باكدج محبي الإسبريسو','حل عملي لمحبي الإسبريسو للاستخدام المنزلي والضيافة.','https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=900&q=88',null,'غامق',array['غامق']::text[],'strong','espresso') returning id)
insert into public.product_variants(product_id,label,weight_g,price,old_price,stock,sort) values ((select id from p),'1.25 كجم',1250,790,860,100,0);
insert into public.order_statuses(code,label_ar,label_en,sort) values ('new','جديد','New',0),('payment_pending','في انتظار الدفع','Payment Pending',1),('payment_review','مراجعة الدفع','Payment Under Review',2),('payment_confirmed','تم تأكيد الدفع','Payment Confirmed',3),('preparing','جاري التحضير','Preparing',4),('shipped','تم الشحن','Shipped',5),('delivered','تم التسليم','Delivered',6),('cancelled','ملغي','Cancelled',7);
insert into public.payment_methods(id,name_ar,name_en,instructions_ar,account_details,requires_proof,sort) values
 ('instapay','إنستا باي','InstaPay','حوّل المبلغ على الحساب ثم ارفع صورة التحويل.','ضع هنا عنوان/رقم إنستا باي',true,1),
 ('vodafone_cash','فودافون كاش','Vodafone Cash','حوّل المبلغ على الرقم ثم ارفع صورة التحويل.','ضع هنا رقم فودافون كاش',true,2),
 ('cod','الدفع عند الاستلام','Cash on Delivery','ادفع للمندوب عند استلام الطلب.',null,false,3);
insert into public.shipping_zones(governorate,price) values ('الدقهلية',70),('دمياط',70),('القاهرة',70),('الجيزة',70),('الإسكندرية',70),('الشرقية',70),('الغربية',70),('القليوبية',70),('المنوفية',70),('البحيرة',70),('كفر الشيخ',70),('بورسعيد',70),('الإسماعيلية',70),('السويس',70),('الفيوم',70),('بني سويف',70),('المنيا',70),('أسيوط',70),('سوهاج',70),('قنا',70),('الأقصر',70),('أسوان',70),('شمال سيناء',70),('جنوب سيناء',70),('البحر الأحمر',70),('مطروح',70),('الوادي الجديد',70);
insert into public.store_settings(key,value) values
 ('whatsapp_number','"201224886344"'),('free_shipping_threshold','600'),('announced_coupon','""'),('store_name','"RAW Coffee House"');
commit;

-- رسوم الدفع عند الاستلام (عدّلها من لوحة الأدمن → طرق الدفع)
update public.payment_methods set fee=20 where id='cod';
